In [3]:
import numpy as np

predictions = np.array([0.2, 0.4, 0.3, 0.1])
print(predictions)
targets = np.array([0.2, 0.4, 0.3, 0.1])
print(targets)
H_x = -np.dot(targets, np.log(predictions))
print('Cross-entropy: ', )
H = -np.dot(targets, np.log(targets))
print('Entropy: ', H)
print('D_kl: ', H_x - H)

predictions = np.array([0.2, 0.4, 0.3, 0.1])
predictions = np.random.permutation(predictions)
print(predictions)
targets = np.array([0.2, 0.4, 0.3, 0.1])
print(targets)
H_x = -np.dot(targets, np.log(predictions))
print('Cross-entropy: ', H_x)
print('Entropy: ', H)
print('D_kl: ', H_x - H)

[0.2 0.4 0.3 0.1]
[0.2 0.4 0.3 0.1]
Cross-entropy: 
Entropy:  1.2798542258336674
D_kl:  0.0
[0.3 0.2 0.1 0.4]
[0.2 0.4 0.3 0.1]
Cross-entropy:  1.6669743269244566
Entropy:  1.2798542258336674
D_kl:  0.3871201010907892


As is said in Wikipedia, KL-divergence is a better measure than cross-entropy of a 'distance' between two distributions (i.e. *models* of data), because it subtracts entropy from cross-entropy to give a pure measure of distance.

$$
D_{KL}(P||Q) = -\mathbb{E}_{p(x)}\log q(x) + \mathbb{E}_{p(x)}\log p(x) = - \sum_{x \in \mathcal{X}} p(x) \log q(x) + \sum_{x \in \mathcal{X}} p(x) \log p(x)
$$

Interestingly, **entropy is the expectation of data under a certain model**, (here $p(x)$)